// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc/TerminalOfflineMsgObtainResponse.proto

package com.aspire.mose.protocol.proto.OfflineMsg;

public final class MsgTerminalOfflineMsgObtainResponse {
  private MsgTerminalOfflineMsgObtainResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TerminalOfflineMsgObtainResponseOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .protocol.TerminalOfflineMsgObtainResponse.ResponseRetCode retCode = 1;
    boolean hasRetCode();
    com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode getRetCode();
    
    // repeated .protocol.TerminalOfflineMsgObtainResponse.MessageInfo message = 2;
    java.util.List<com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo> 
        getMessageList();
    com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo getMessage(int index);
    int getMessageCount();
  }
  public static final class TerminalOfflineMsgObtainResponse extends
      com.google.protobuf.GeneratedMessageLite
      implements TerminalOfflineMsgObtainResponseOrBuilder {
    // Use TerminalOfflineMsgObtainResponse.newBuilder() to construct.
    private TerminalOfflineMsgObtainResponse(Builder builder) {
      super(builder);
    }
    private TerminalOfflineMsgObtainResponse(boolean noInit) {}
    
    private static final TerminalOfflineMsgObtainResponse defaultInstance;
    public static TerminalOfflineMsgObtainResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public TerminalOfflineMsgObtainResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum ResponseRetCode
        implements com.google.protobuf.Internal.EnumLite {
      SUCCESS(0, 0),
      OTHERFAIL(1, 1),
      SYSTEMINTERNALlERROR(2, 2),
      SYSTEMBUSY(3, 3),
      MESSAGEFORMATERROR(4, 101),
      MESSAGEFIELDVALUEERROR(5, 102),
      DEVICENOTEXIST(6, 201),
      NOOFFLINEMESSAGE(7, 302),
      ;
      
      public static final int SUCCESS_VALUE = 0;
      public static final int OTHERFAIL_VALUE = 1;
      public static final int SYSTEMINTERNALlERROR_VALUE = 2;
      public static final int SYSTEMBUSY_VALUE = 3;
      public static final int MESSAGEFORMATERROR_VALUE = 101;
      public static final int MESSAGEFIELDVALUEERROR_VALUE = 102;
      public static final int DEVICENOTEXIST_VALUE = 201;
      public static final int NOOFFLINEMESSAGE_VALUE = 302;
      
      
      public final int getNumber() { return value; }
      
      public static ResponseRetCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return OTHERFAIL;
          case 2: return SYSTEMINTERNALlERROR;
          case 3: return SYSTEMBUSY;
          case 101: return MESSAGEFORMATERROR;
          case 102: return MESSAGEFIELDVALUEERROR;
          case 201: return DEVICENOTEXIST;
          case 302: return NOOFFLINEMESSAGE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ResponseRetCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResponseRetCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseRetCode>() {
              public ResponseRetCode findValueByNumber(int number) {
                return ResponseRetCode.valueOf(number);
              }
            };
      
      private final int value;
      
      private ResponseRetCode(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protocol.TerminalOfflineMsgObtainResponse.ResponseRetCode)
    }
    
    public interface MessageInfoOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {
      
      // required .protocol.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat msgFormat = 1;
      boolean hasMsgFormat();
      com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat getMsgFormat();
      
      // optional .protocol.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode msgMode = 2;
      boolean hasMsgMode();
      com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode getMsgMode();
      
      // required bytes msgContent = 3;
      boolean hasMsgContent();
      com.google.protobuf.ByteString getMsgContent();
      
      // required string appId = 4;
      boolean hasAppId();
      String getAppId();
    }
    public static final class MessageInfo extends
        com.google.protobuf.GeneratedMessageLite
        implements MessageInfoOrBuilder {
      // Use MessageInfo.newBuilder() to construct.
      private MessageInfo(Builder builder) {
        super(builder);
      }
      private MessageInfo(boolean noInit) {}
      
      private static final MessageInfo defaultInstance;
      public static MessageInfo getDefaultInstance() {
        return defaultInstance;
      }
      
      public MessageInfo getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public enum MessageFormat
          implements com.google.protobuf.Internal.EnumLite {
        BINARY(0, 0),
        TEXT(1, 1),
        ;
        
        public static final int BINARY_VALUE = 0;
        public static final int TEXT_VALUE = 1;
        
        
        public final int getNumber() { return value; }
        
        public static MessageFormat valueOf(int value) {
          switch (value) {
            case 0: return BINARY;
            case 1: return TEXT;
            default: return null;
          }
        }
        
        public static com.google.protobuf.Internal.EnumLiteMap<MessageFormat>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<MessageFormat>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<MessageFormat>() {
                public MessageFormat findValueByNumber(int number) {
                  return MessageFormat.valueOf(number);
                }
              };
        
        private final int value;
        
        private MessageFormat(int index, int value) {
          this.value = value;
        }
        
        // @@protoc_insertion_point(enum_scope:protocol.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat)
      }
      
      public enum MessageMode
          implements com.google.protobuf.Internal.EnumLite {
        NOTIFICATIONBAR(0, 0),
        INBOX(1, 1),
        APPLICATIONICON(2, 2),
        APPLICATION(3, 3),
        APPLICATIONWITHUSERCONFIRM(4, 4),
        ;
        
        public static final int NOTIFICATIONBAR_VALUE = 0;
        public static final int INBOX_VALUE = 1;
        public static final int APPLICATIONICON_VALUE = 2;
        public static final int APPLICATION_VALUE = 3;
        public static final int APPLICATIONWITHUSERCONFIRM_VALUE = 4;
        
        
        public final int getNumber() { return value; }
        
        public static MessageMode valueOf(int value) {
          switch (value) {
            case 0: return NOTIFICATIONBAR;
            case 1: return INBOX;
            case 2: return APPLICATIONICON;
            case 3: return APPLICATION;
            case 4: return APPLICATIONWITHUSERCONFIRM;
            default: return null;
          }
        }
        
        public static com.google.protobuf.Internal.EnumLiteMap<MessageMode>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<MessageMode>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<MessageMode>() {
                public MessageMode findValueByNumber(int number) {
                  return MessageMode.valueOf(number);
                }
              };
        
        private final int value;
        
        private MessageMode(int index, int value) {
          this.value = value;
        }
        
        // @@protoc_insertion_point(enum_scope:protocol.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode)
      }
      
      private int bitField0_;
      // required .protocol.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat msgFormat = 1;
      public static final int MSGFORMAT_FIELD_NUMBER = 1;
      private com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat msgFormat_;
      public boolean hasMsgFormat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat getMsgFormat() {
        return msgFormat_;
      }
      
      // optional .protocol.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode msgMode = 2;
      public static final int MSGMODE_FIELD_NUMBER = 2;
      private com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode msgMode_;
      public boolean hasMsgMode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode getMsgMode() {
        return msgMode_;
      }
      
      // required bytes msgContent = 3;
      public static final int MSGCONTENT_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString msgContent_;
      public boolean hasMsgContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getMsgContent() {
        return msgContent_;
      }
      
      // required string appId = 4;
      public static final int APPID_FIELD_NUMBER = 4;
      private java.lang.Object appId_;
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getAppId() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            appId_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        msgFormat_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat.BINARY;
        msgMode_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode.NOTIFICATIONBAR;
        msgContent_ = com.google.protobuf.ByteString.EMPTY;
        appId_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasMsgFormat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMsgContent()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAppId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, msgFormat_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, msgMode_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, msgContent_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getAppIdBytes());
        }
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, msgFormat_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, msgMode_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, msgContent_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getAppIdBytes());
        }
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo, Builder>
          implements com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfoOrBuilder {
        // Construct using com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          msgFormat_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat.BINARY;
          bitField0_ = (bitField0_ & ~0x00000001);
          msgMode_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode.NOTIFICATIONBAR;
          bitField0_ = (bitField0_ & ~0x00000002);
          msgContent_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          appId_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo getDefaultInstanceForType() {
          return com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.getDefaultInstance();
        }
        
        public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo build() {
          com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo buildPartial() {
          com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo result = new com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.msgFormat_ = msgFormat_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.msgMode_ = msgMode_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.msgContent_ = msgContent_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.appId_ = appId_;
          result.bitField0_ = to_bitField0_;
          return result;
        }
        
        public Builder mergeFrom(com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo other) {
          if (other == com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.getDefaultInstance()) return this;
          if (other.hasMsgFormat()) {
            setMsgFormat(other.getMsgFormat());
          }
          if (other.hasMsgMode()) {
            setMsgMode(other.getMsgMode());
          }
          if (other.hasMsgContent()) {
            setMsgContent(other.getMsgContent());
          }
          if (other.hasAppId()) {
            setAppId(other.getAppId());
          }
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasMsgFormat()) {
            
            return false;
          }
          if (!hasMsgContent()) {
            
            return false;
          }
          if (!hasAppId()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                
                return this;
              default: {
                if (!parseUnknownField(input, extensionRegistry, tag)) {
                  
                  return this;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat value = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat.valueOf(rawValue);
                if (value != null) {
                  bitField0_ |= 0x00000001;
                  msgFormat_ = value;
                }
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode value = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode.valueOf(rawValue);
                if (value != null) {
                  bitField0_ |= 0x00000002;
                  msgMode_ = value;
                }
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                msgContent_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                appId_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required .protocol.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat msgFormat = 1;
        private com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat msgFormat_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat.BINARY;
        public boolean hasMsgFormat() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat getMsgFormat() {
          return msgFormat_;
        }
        public Builder setMsgFormat(com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          msgFormat_ = value;
          
          return this;
        }
        public Builder clearMsgFormat() {
          bitField0_ = (bitField0_ & ~0x00000001);
          msgFormat_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageFormat.BINARY;
          
          return this;
        }
        
        // optional .protocol.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode msgMode = 2;
        private com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode msgMode_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode.NOTIFICATIONBAR;
        public boolean hasMsgMode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode getMsgMode() {
          return msgMode_;
        }
        public Builder setMsgMode(com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          msgMode_ = value;
          
          return this;
        }
        public Builder clearMsgMode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          msgMode_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.MessageMode.NOTIFICATIONBAR;
          
          return this;
        }
        
        // required bytes msgContent = 3;
        private com.google.protobuf.ByteString msgContent_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasMsgContent() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public com.google.protobuf.ByteString getMsgContent() {
          return msgContent_;
        }
        public Builder setMsgContent(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          msgContent_ = value;
          
          return this;
        }
        public Builder clearMsgContent() {
          bitField0_ = (bitField0_ & ~0x00000004);
          msgContent_ = getDefaultInstance().getMsgContent();
          
          return this;
        }
        
        // required string appId = 4;
        private java.lang.Object appId_ = "";
        public boolean hasAppId() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public String getAppId() {
          java.lang.Object ref = appId_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            appId_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setAppId(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          appId_ = value;
          
          return this;
        }
        public Builder clearAppId() {
          bitField0_ = (bitField0_ & ~0x00000008);
          appId_ = getDefaultInstance().getAppId();
          
          return this;
        }
        void setAppId(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000008;
          appId_ = value;
          
        }
        
        // @@protoc_insertion_point(builder_scope:protocol.TerminalOfflineMsgObtainResponse.MessageInfo)
      }
      
      static {
        defaultInstance = new MessageInfo(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:protocol.TerminalOfflineMsgObtainResponse.MessageInfo)
    }
    
    private int bitField0_;
    // required .protocol.TerminalOfflineMsgObtainResponse.ResponseRetCode retCode = 1;
    public static final int RETCODE_FIELD_NUMBER = 1;
    private com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode retCode_;
    public boolean hasRetCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode getRetCode() {
      return retCode_;
    }
    
    // repeated .protocol.TerminalOfflineMsgObtainResponse.MessageInfo message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.util.List<com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo> message_;
    public java.util.List<com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo> getMessageList() {
      return message_;
    }
    public java.util.List<? extends com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfoOrBuilder> 
        getMessageOrBuilderList() {
      return message_;
    }
    public int getMessageCount() {
      return message_.size();
    }
    public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo getMessage(int index) {
      return message_.get(index);
    }
    public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfoOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }
    
    private void initFields() {
      retCode_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode.SUCCESS;
      message_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRetCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMessageCount(); i++) {
        if (!getMessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, retCode_.getNumber());
      }
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(2, message_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, retCode_.getNumber());
      }
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, message_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse, Builder>
        implements com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponseOrBuilder {
      // Construct using com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        retCode_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse getDefaultInstanceForType() {
        return com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse build() {
        com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse buildPartial() {
        com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse result = new com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retCode_ = retCode_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          message_ = java.util.Collections.unmodifiableList(message_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse other) {
        if (other == com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.getDefaultInstance()) return this;
        if (other.hasRetCode()) {
          setRetCode(other.getRetCode());
        }
        if (!other.message_.isEmpty()) {
          if (message_.isEmpty()) {
            message_ = other.message_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMessageIsMutable();
            message_.addAll(other.message_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRetCode()) {
          
          return false;
        }
        for (int i = 0; i < getMessageCount(); i++) {
          if (!getMessage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode value = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                retCode_ = value;
              }
              break;
            }
            case 18: {
              com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.Builder subBuilder = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .protocol.TerminalOfflineMsgObtainResponse.ResponseRetCode retCode = 1;
      private com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode retCode_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode.SUCCESS;
      public boolean hasRetCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode getRetCode() {
        return retCode_;
      }
      public Builder setRetCode(com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        retCode_ = value;
        
        return this;
      }
      public Builder clearRetCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retCode_ = com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.ResponseRetCode.SUCCESS;
        
        return this;
      }
      
      // repeated .protocol.TerminalOfflineMsgObtainResponse.MessageInfo message = 2;
      private java.util.List<com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          message_ = new java.util.ArrayList<com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo>(message_);
          bitField0_ |= 0x00000002;
         }
      }
      
      public java.util.List<com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo> getMessageList() {
        return java.util.Collections.unmodifiableList(message_);
      }
      public int getMessageCount() {
        return message_.size();
      }
      public com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo getMessage(int index) {
        return message_.get(index);
      }
      public Builder setMessage(
          int index, com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageIsMutable();
        message_.set(index, value);
        
        return this;
      }
      public Builder setMessage(
          int index, com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.Builder builderForValue) {
        ensureMessageIsMutable();
        message_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addMessage(com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageIsMutable();
        message_.add(value);
        
        return this;
      }
      public Builder addMessage(
          int index, com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageIsMutable();
        message_.add(index, value);
        
        return this;
      }
      public Builder addMessage(
          com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.Builder builderForValue) {
        ensureMessageIsMutable();
        message_.add(builderForValue.build());
        
        return this;
      }
      public Builder addMessage(
          int index, com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo.Builder builderForValue) {
        ensureMessageIsMutable();
        message_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllMessage(
          java.lang.Iterable<? extends com.aspire.mose.protocol.proto.OfflineMsg.MsgTerminalOfflineMsgObtainResponse.TerminalOfflineMsgObtainResponse.MessageInfo> values) {
        ensureMessageIsMutable();
        super.addAll(values, message_);
        
        return this;
      }
      public Builder clearMessage() {
        message_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }
      public Builder removeMessage(int index) {
        ensureMessageIsMutable();
        message_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.TerminalOfflineMsgObtainResponse)
    }
    
    static {
      defaultInstance = new TerminalOfflineMsgObtainResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.TerminalOfflineMsgObtainResponse)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
