// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePushRequest.proto

package com.aspire.mose.protocol.proto.msgpush;

public final class MsgMessagePushRequest {
  private MsgMessagePushRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessagePushRequestOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string deviceId = 1;
    boolean hasDeviceId();
    String getDeviceId();
    
    // required string userId = 2;
    boolean hasUserId();
    String getUserId();
    
    // optional string userToken = 3;
    boolean hasUserToken();
    String getUserToken();
    
    // required string appId = 4;
    boolean hasAppId();
    String getAppId();
    
    // required string msgId = 5;
    boolean hasMsgId();
    String getMsgId();
    
    // required bool stateReport = 6;
    boolean hasStateReport();
    boolean getStateReport();
    
    // required .protocol.MessagePushRequest.MessageInfo message = 7;
    boolean hasMessage();
    com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo getMessage();
  }
  public static final class MessagePushRequest extends
      com.google.protobuf.GeneratedMessageLite
      implements MessagePushRequestOrBuilder {
    // Use MessagePushRequest.newBuilder() to construct.
    private MessagePushRequest(Builder builder) {
      super(builder);
    }
    private MessagePushRequest(boolean noInit) {}
    
    private static final MessagePushRequest defaultInstance;
    public static MessagePushRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessagePushRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public interface MessageInfoOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {
      
      // required .protocol.MessagePushRequest.MessageInfo.MessageFormat msgFormat = 1;
      boolean hasMsgFormat();
      com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat getMsgFormat();
      
      // optional .protocol.MessagePushRequest.MessageInfo.MessageMode msgMode = 2;
      boolean hasMsgMode();
      com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode getMsgMode();
      
      // required bytes msgContent = 3;
      boolean hasMsgContent();
      com.google.protobuf.ByteString getMsgContent();
    }
    public static final class MessageInfo extends
        com.google.protobuf.GeneratedMessageLite
        implements MessageInfoOrBuilder {
      // Use MessageInfo.newBuilder() to construct.
      private MessageInfo(Builder builder) {
        super(builder);
      }
      private MessageInfo(boolean noInit) {}
      
      private static final MessageInfo defaultInstance;
      public static MessageInfo getDefaultInstance() {
        return defaultInstance;
      }
      
      public MessageInfo getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public enum MessageFormat
          implements com.google.protobuf.Internal.EnumLite {
        BINARY(0, 0),
        TEXT(1, 1),
        ;
        
        public static final int BINARY_VALUE = 0;
        public static final int TEXT_VALUE = 1;
        
        
        public final int getNumber() { return value; }
        
        public static MessageFormat valueOf(int value) {
          switch (value) {
            case 0: return BINARY;
            case 1: return TEXT;
            default: return null;
          }
        }
        
        public static com.google.protobuf.Internal.EnumLiteMap<MessageFormat>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<MessageFormat>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<MessageFormat>() {
                public MessageFormat findValueByNumber(int number) {
                  return MessageFormat.valueOf(number);
                }
              };
        
        private final int value;
        
        private MessageFormat(int index, int value) {
          this.value = value;
        }
        
        // @@protoc_insertion_point(enum_scope:protocol.MessagePushRequest.MessageInfo.MessageFormat)
      }
      
      public enum MessageMode
          implements com.google.protobuf.Internal.EnumLite {
        NOTIFICATIONBAR(0, 0),
        INBOX(1, 1),
        APPLICATIONICON(2, 2),
        APPLICATION(3, 3),
        APPLICATIONWITHUSERCONFIRM(4, 4),
        ;
        
        public static final int NOTIFICATIONBAR_VALUE = 0;
        public static final int INBOX_VALUE = 1;
        public static final int APPLICATIONICON_VALUE = 2;
        public static final int APPLICATION_VALUE = 3;
        public static final int APPLICATIONWITHUSERCONFIRM_VALUE = 4;
        
        
        public final int getNumber() { return value; }
        
        public static MessageMode valueOf(int value) {
          switch (value) {
            case 0: return NOTIFICATIONBAR;
            case 1: return INBOX;
            case 2: return APPLICATIONICON;
            case 3: return APPLICATION;
            case 4: return APPLICATIONWITHUSERCONFIRM;
            default: return null;
          }
        }
        
        public static com.google.protobuf.Internal.EnumLiteMap<MessageMode>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<MessageMode>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<MessageMode>() {
                public MessageMode findValueByNumber(int number) {
                  return MessageMode.valueOf(number);
                }
              };
        
        private final int value;
        
        private MessageMode(int index, int value) {
          this.value = value;
        }
        
        // @@protoc_insertion_point(enum_scope:protocol.MessagePushRequest.MessageInfo.MessageMode)
      }
      
      private int bitField0_;
      // required .protocol.MessagePushRequest.MessageInfo.MessageFormat msgFormat = 1;
      public static final int MSGFORMAT_FIELD_NUMBER = 1;
      private com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat msgFormat_;
      public boolean hasMsgFormat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat getMsgFormat() {
        return msgFormat_;
      }
      
      // optional .protocol.MessagePushRequest.MessageInfo.MessageMode msgMode = 2;
      public static final int MSGMODE_FIELD_NUMBER = 2;
      private com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode msgMode_;
      public boolean hasMsgMode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode getMsgMode() {
        return msgMode_;
      }
      
      // required bytes msgContent = 3;
      public static final int MSGCONTENT_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString msgContent_;
      public boolean hasMsgContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getMsgContent() {
        return msgContent_;
      }
      
      private void initFields() {
        msgFormat_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat.BINARY;
        msgMode_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode.NOTIFICATIONBAR;
        msgContent_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasMsgFormat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMsgContent()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, msgFormat_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, msgMode_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, msgContent_);
        }
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, msgFormat_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, msgMode_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, msgContent_);
        }
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo, Builder>
          implements com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfoOrBuilder {
        // Construct using com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          msgFormat_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat.BINARY;
          bitField0_ = (bitField0_ & ~0x00000001);
          msgMode_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode.NOTIFICATIONBAR;
          bitField0_ = (bitField0_ & ~0x00000002);
          msgContent_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo getDefaultInstanceForType() {
          return com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.getDefaultInstance();
        }
        
        public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo build() {
          com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo buildPartial() {
          com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo result = new com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.msgFormat_ = msgFormat_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.msgMode_ = msgMode_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.msgContent_ = msgContent_;
          result.bitField0_ = to_bitField0_;
          return result;
        }
        
        public Builder mergeFrom(com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo other) {
          if (other == com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.getDefaultInstance()) return this;
          if (other.hasMsgFormat()) {
            setMsgFormat(other.getMsgFormat());
          }
          if (other.hasMsgMode()) {
            setMsgMode(other.getMsgMode());
          }
          if (other.hasMsgContent()) {
            setMsgContent(other.getMsgContent());
          }
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasMsgFormat()) {
            
            return false;
          }
          if (!hasMsgContent()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                
                return this;
              default: {
                if (!parseUnknownField(input, extensionRegistry, tag)) {
                  
                  return this;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat value = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat.valueOf(rawValue);
                if (value != null) {
                  bitField0_ |= 0x00000001;
                  msgFormat_ = value;
                }
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode value = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode.valueOf(rawValue);
                if (value != null) {
                  bitField0_ |= 0x00000002;
                  msgMode_ = value;
                }
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                msgContent_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required .protocol.MessagePushRequest.MessageInfo.MessageFormat msgFormat = 1;
        private com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat msgFormat_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat.BINARY;
        public boolean hasMsgFormat() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat getMsgFormat() {
          return msgFormat_;
        }
        public Builder setMsgFormat(com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          msgFormat_ = value;
          
          return this;
        }
        public Builder clearMsgFormat() {
          bitField0_ = (bitField0_ & ~0x00000001);
          msgFormat_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageFormat.BINARY;
          
          return this;
        }
        
        // optional .protocol.MessagePushRequest.MessageInfo.MessageMode msgMode = 2;
        private com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode msgMode_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode.NOTIFICATIONBAR;
        public boolean hasMsgMode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode getMsgMode() {
          return msgMode_;
        }
        public Builder setMsgMode(com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          msgMode_ = value;
          
          return this;
        }
        public Builder clearMsgMode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          msgMode_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.MessageMode.NOTIFICATIONBAR;
          
          return this;
        }
        
        // required bytes msgContent = 3;
        private com.google.protobuf.ByteString msgContent_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasMsgContent() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public com.google.protobuf.ByteString getMsgContent() {
          return msgContent_;
        }
        public Builder setMsgContent(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          msgContent_ = value;
          
          return this;
        }
        public Builder clearMsgContent() {
          bitField0_ = (bitField0_ & ~0x00000004);
          msgContent_ = getDefaultInstance().getMsgContent();
          
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:protocol.MessagePushRequest.MessageInfo)
      }
      
      static {
        defaultInstance = new MessageInfo(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:protocol.MessagePushRequest.MessageInfo)
    }
    
    private int bitField0_;
    // required string deviceId = 1;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string userToken = 3;
    public static final int USERTOKEN_FIELD_NUMBER = 3;
    private java.lang.Object userToken_;
    public boolean hasUserToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getUserToken() {
      java.lang.Object ref = userToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserTokenBytes() {
      java.lang.Object ref = userToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string appId = 4;
    public static final int APPID_FIELD_NUMBER = 4;
    private java.lang.Object appId_;
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          appId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string msgId = 5;
    public static final int MSGID_FIELD_NUMBER = 5;
    private java.lang.Object msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msgId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bool stateReport = 6;
    public static final int STATEREPORT_FIELD_NUMBER = 6;
    private boolean stateReport_;
    public boolean hasStateReport() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getStateReport() {
      return stateReport_;
    }
    
    // required .protocol.MessagePushRequest.MessageInfo message = 7;
    public static final int MESSAGE_FIELD_NUMBER = 7;
    private com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo getMessage() {
      return message_;
    }
    
    private void initFields() {
      deviceId_ = "";
      userId_ = "";
      userToken_ = "";
      appId_ = "";
      msgId_ = "";
      stateReport_ = false;
      message_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStateReport()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAppIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, stateReport_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, message_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAppIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, stateReport_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, message_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest, Builder>
        implements com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequestOrBuilder {
      // Construct using com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        appId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        stateReport_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        message_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest getDefaultInstanceForType() {
        return com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest build() {
        com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest buildPartial() {
        com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest result = new com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userToken_ = userToken_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.stateReport_ = stateReport_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest other) {
        if (other == com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserToken()) {
          setUserToken(other.getUserToken());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasStateReport()) {
          setStateReport(other.getStateReport());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (!hasMsgId()) {
          
          return false;
        }
        if (!hasStateReport()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        if (!getMessage().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userToken_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              appId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msgId_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              stateReport_ = input.readBool();
              break;
            }
            case 58: {
              com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.Builder subBuilder = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.newBuilder();
              if (hasMessage()) {
                subBuilder.mergeFrom(getMessage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string deviceId = 1;
      private java.lang.Object deviceId_ = "";
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        
        return this;
      }
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        
        return this;
      }
      void setDeviceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        
      }
      
      // required string userId = 2;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userId_ = value;
        
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = getDefaultInstance().getUserId();
        
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        
      }
      
      // optional string userToken = 3;
      private java.lang.Object userToken_ = "";
      public boolean hasUserToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getUserToken() {
        java.lang.Object ref = userToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userToken_ = value;
        
        return this;
      }
      public Builder clearUserToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userToken_ = getDefaultInstance().getUserToken();
        
        return this;
      }
      void setUserToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        userToken_ = value;
        
      }
      
      // required string appId = 4;
      private java.lang.Object appId_ = "";
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAppId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        appId_ = value;
        
        return this;
      }
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        appId_ = getDefaultInstance().getAppId();
        
        return this;
      }
      void setAppId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        appId_ = value;
        
      }
      
      // required string msgId = 5;
      private java.lang.Object msgId_ = "";
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsgId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgId_ = value;
        
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgId_ = getDefaultInstance().getMsgId();
        
        return this;
      }
      void setMsgId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        msgId_ = value;
        
      }
      
      // required bool stateReport = 6;
      private boolean stateReport_ ;
      public boolean hasStateReport() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getStateReport() {
        return stateReport_;
      }
      public Builder setStateReport(boolean value) {
        bitField0_ |= 0x00000020;
        stateReport_ = value;
        
        return this;
      }
      public Builder clearStateReport() {
        bitField0_ = (bitField0_ & ~0x00000020);
        stateReport_ = false;
        
        return this;
      }
      
      // required .protocol.MessagePushRequest.MessageInfo message = 7;
      private com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo message_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.getDefaultInstance();
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo getMessage() {
        return message_;
      }
      public Builder setMessage(com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setMessage(
          com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.Builder builderForValue) {
        message_ = builderForValue.build();
        
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergeMessage(com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo value) {
        if (((bitField0_ & 0x00000040) == 0x00000040) &&
            message_ != com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.getDefaultInstance()) {
          message_ =
            com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.newBuilder(message_).mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearMessage() {
        message_ = com.aspire.mose.protocol.proto.msgpush.MsgMessagePushRequest.MessagePushRequest.MessageInfo.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.MessagePushRequest)
    }
    
    static {
      defaultInstance = new MessagePushRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.MessagePushRequest)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
