// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HandShakeFinish.proto

package com.aspire.mose.protocol.handshake;

public final class MsgHandShakeFinish {
  private MsgHandShakeFinish() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface HandShakeFinishOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .protocol.ProtocolRetCode RetResult = 1;
    boolean hasRetResult();
    com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult();
  }
  public static final class HandShakeFinish extends
      com.google.protobuf.GeneratedMessageLite
      implements HandShakeFinishOrBuilder {
    // Use HandShakeFinish.newBuilder() to construct.
    private HandShakeFinish(Builder builder) {
      super(builder);
    }
    private HandShakeFinish(boolean noInit) {}
    
    private static final HandShakeFinish defaultInstance;
    public static HandShakeFinish getDefaultInstance() {
      return defaultInstance;
    }
    
    public HandShakeFinish getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .protocol.ProtocolRetCode RetResult = 1;
    public static final int RETRESULT_FIELD_NUMBER = 1;
    private com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode retResult_;
    public boolean hasRetResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult() {
      return retResult_;
    }
    
    private void initFields() {
      retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRetResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, retResult_.getNumber());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, retResult_.getNumber());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish, Builder>
        implements com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinishOrBuilder {
      // Construct using com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish getDefaultInstanceForType() {
        return com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish build() {
        com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish buildPartial() {
        com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish result = new com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retResult_ = retResult_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish other) {
        if (other == com.aspire.mose.protocol.handshake.MsgHandShakeFinish.HandShakeFinish.getDefaultInstance()) return this;
        if (other.hasRetResult()) {
          setRetResult(other.getRetResult());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRetResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode value = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                retResult_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .protocol.ProtocolRetCode RetResult = 1;
      private com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
      public boolean hasRetResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult() {
        return retResult_;
      }
      public Builder setRetResult(com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        retResult_ = value;
        
        return this;
      }
      public Builder clearRetResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.HandShakeFinish)
    }
    
    static {
      defaultInstance = new HandShakeFinish(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.HandShakeFinish)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
