// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecuCheckProgClientReq.proto

package com.aspire.mose.protocol.handshake;

public final class MsgSecuCheckProgClientReq {
  private MsgSecuCheckProgClientReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SecuCheckProgClientReqOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string SessionId = 1;
    boolean hasSessionId();
    String getSessionId();
  }
  public static final class SecuCheckProgClientReq extends
      com.google.protobuf.GeneratedMessageLite
      implements SecuCheckProgClientReqOrBuilder {
    // Use SecuCheckProgClientReq.newBuilder() to construct.
    private SecuCheckProgClientReq(Builder builder) {
      super(builder);
    }
    private SecuCheckProgClientReq(boolean noInit) {}
    
    private static final SecuCheckProgClientReq defaultInstance;
    public static SecuCheckProgClientReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public SecuCheckProgClientReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string SessionId = 1;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    private java.lang.Object sessionId_;
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessionId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sessionId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSessionIdBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSessionIdBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq, Builder>
        implements com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReqOrBuilder {
      // Construct using com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq getDefaultInstanceForType() {
        return com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq build() {
        com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq buildPartial() {
        com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq result = new com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessionId_ = sessionId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq other) {
        if (other == com.aspire.mose.protocol.handshake.MsgSecuCheckProgClientReq.SecuCheckProgClientReq.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSessionId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string SessionId = 1;
      private java.lang.Object sessionId_ = "";
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessionId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionId_ = value;
        
        return this;
      }
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = getDefaultInstance().getSessionId();
        
        return this;
      }
      void setSessionId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.SecuCheckProgClientReq)
    }
    
    static {
      defaultInstance = new SecuCheckProgClientReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.SecuCheckProgClientReq)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
