// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecuCheckProgServerResp.proto

package com.aspire.mose.protocol.handshake;

public final class MsgSecuCheckProgServerResp {
  private MsgSecuCheckProgServerResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SecuCheckProgServerRespOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .protocol.ProtocolRetCode RetResult = 1;
    boolean hasRetResult();
    com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult();
    
    // optional uint32 CipherSize = 2;
    boolean hasCipherSize();
    int getCipherSize();
    
    // optional bytes SecuCheckProg = 3;
    boolean hasSecuCheckProg();
    com.google.protobuf.ByteString getSecuCheckProg();
  }
  public static final class SecuCheckProgServerResp extends
      com.google.protobuf.GeneratedMessageLite
      implements SecuCheckProgServerRespOrBuilder {
    // Use SecuCheckProgServerResp.newBuilder() to construct.
    private SecuCheckProgServerResp(Builder builder) {
      super(builder);
    }
    private SecuCheckProgServerResp(boolean noInit) {}
    
    private static final SecuCheckProgServerResp defaultInstance;
    public static SecuCheckProgServerResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public SecuCheckProgServerResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .protocol.ProtocolRetCode RetResult = 1;
    public static final int RETRESULT_FIELD_NUMBER = 1;
    private com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode retResult_;
    public boolean hasRetResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult() {
      return retResult_;
    }
    
    // optional uint32 CipherSize = 2;
    public static final int CIPHERSIZE_FIELD_NUMBER = 2;
    private int cipherSize_;
    public boolean hasCipherSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCipherSize() {
      return cipherSize_;
    }
    
    // optional bytes SecuCheckProg = 3;
    public static final int SECUCHECKPROG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString secuCheckProg_;
    public boolean hasSecuCheckProg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getSecuCheckProg() {
      return secuCheckProg_;
    }
    
    private void initFields() {
      retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
      cipherSize_ = 0;
      secuCheckProg_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRetResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, retResult_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, cipherSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, secuCheckProg_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, retResult_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, cipherSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, secuCheckProg_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp, Builder>
        implements com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerRespOrBuilder {
      // Construct using com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        cipherSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        secuCheckProg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp getDefaultInstanceForType() {
        return com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp build() {
        com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp buildPartial() {
        com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp result = new com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retResult_ = retResult_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cipherSize_ = cipherSize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.secuCheckProg_ = secuCheckProg_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp other) {
        if (other == com.aspire.mose.protocol.handshake.MsgSecuCheckProgServerResp.SecuCheckProgServerResp.getDefaultInstance()) return this;
        if (other.hasRetResult()) {
          setRetResult(other.getRetResult());
        }
        if (other.hasCipherSize()) {
          setCipherSize(other.getCipherSize());
        }
        if (other.hasSecuCheckProg()) {
          setSecuCheckProg(other.getSecuCheckProg());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRetResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode value = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                retResult_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cipherSize_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              secuCheckProg_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .protocol.ProtocolRetCode RetResult = 1;
      private com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
      public boolean hasRetResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult() {
        return retResult_;
      }
      public Builder setRetResult(com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        retResult_ = value;
        
        return this;
      }
      public Builder clearRetResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
        
        return this;
      }
      
      // optional uint32 CipherSize = 2;
      private int cipherSize_ ;
      public boolean hasCipherSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCipherSize() {
        return cipherSize_;
      }
      public Builder setCipherSize(int value) {
        bitField0_ |= 0x00000002;
        cipherSize_ = value;
        
        return this;
      }
      public Builder clearCipherSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cipherSize_ = 0;
        
        return this;
      }
      
      // optional bytes SecuCheckProg = 3;
      private com.google.protobuf.ByteString secuCheckProg_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasSecuCheckProg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getSecuCheckProg() {
        return secuCheckProg_;
      }
      public Builder setSecuCheckProg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        secuCheckProg_ = value;
        
        return this;
      }
      public Builder clearSecuCheckProg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        secuCheckProg_ = getDefaultInstance().getSecuCheckProg();
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.SecuCheckProgServerResp)
    }
    
    static {
      defaultInstance = new SecuCheckProgServerResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.SecuCheckProgServerResp)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
