// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc/ConnectionHeartbeatDetectionResponse.proto

package com.aspire.mose.protocol.proto;

public final class MsgConnectionHeartbeatDetectionResponse {
  private MsgConnectionHeartbeatDetectionResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ConnectionHeartbeatDetectionResponseOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .protocol.ConnectionHeartbeatDetectionResponse.ResponseRetCode retCode = 1;
    boolean hasRetCode();
    com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode getRetCode();
    
    // required uint32 offlineMessages = 2;
    boolean hasOfflineMessages();
    int getOfflineMessages();
  }
  public static final class ConnectionHeartbeatDetectionResponse extends
      com.google.protobuf.GeneratedMessageLite
      implements ConnectionHeartbeatDetectionResponseOrBuilder {
    // Use ConnectionHeartbeatDetectionResponse.newBuilder() to construct.
    private ConnectionHeartbeatDetectionResponse(Builder builder) {
      super(builder);
    }
    private ConnectionHeartbeatDetectionResponse(boolean noInit) {}
    
    private static final ConnectionHeartbeatDetectionResponse defaultInstance;
    public static ConnectionHeartbeatDetectionResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConnectionHeartbeatDetectionResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum ResponseRetCode
        implements com.google.protobuf.Internal.EnumLite {
      SUCCESS(0, 0),
      OTHERFAIL(1, 1),
      SYSTEMINTERNALlERROR(2, 2),
      SYSTEMBUSY(3, 3),
      ;
      
      public static final int SUCCESS_VALUE = 0;
      public static final int OTHERFAIL_VALUE = 1;
      public static final int SYSTEMINTERNALlERROR_VALUE = 2;
      public static final int SYSTEMBUSY_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static ResponseRetCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return OTHERFAIL;
          case 2: return SYSTEMINTERNALlERROR;
          case 3: return SYSTEMBUSY;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ResponseRetCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResponseRetCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseRetCode>() {
              public ResponseRetCode findValueByNumber(int number) {
                return ResponseRetCode.valueOf(number);
              }
            };
      
      private final int value;
      
      private ResponseRetCode(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protocol.ConnectionHeartbeatDetectionResponse.ResponseRetCode)
    }
    
    private int bitField0_;
    // required .protocol.ConnectionHeartbeatDetectionResponse.ResponseRetCode retCode = 1;
    public static final int RETCODE_FIELD_NUMBER = 1;
    private com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode retCode_;
    public boolean hasRetCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode getRetCode() {
      return retCode_;
    }
    
    // required uint32 offlineMessages = 2;
    public static final int OFFLINEMESSAGES_FIELD_NUMBER = 2;
    private int offlineMessages_;
    public boolean hasOfflineMessages() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getOfflineMessages() {
      return offlineMessages_;
    }
    
    private void initFields() {
      retCode_ = com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode.SUCCESS;
      offlineMessages_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRetCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOfflineMessages()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, retCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, offlineMessages_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, retCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, offlineMessages_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse, Builder>
        implements com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponseOrBuilder {
      // Construct using com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        retCode_ = com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        offlineMessages_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse getDefaultInstanceForType() {
        return com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse build() {
        com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse buildPartial() {
        com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse result = new com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retCode_ = retCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.offlineMessages_ = offlineMessages_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse other) {
        if (other == com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.getDefaultInstance()) return this;
        if (other.hasRetCode()) {
          setRetCode(other.getRetCode());
        }
        if (other.hasOfflineMessages()) {
          setOfflineMessages(other.getOfflineMessages());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRetCode()) {
          
          return false;
        }
        if (!hasOfflineMessages()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode value = com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                retCode_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              offlineMessages_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .protocol.ConnectionHeartbeatDetectionResponse.ResponseRetCode retCode = 1;
      private com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode retCode_ = com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode.SUCCESS;
      public boolean hasRetCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode getRetCode() {
        return retCode_;
      }
      public Builder setRetCode(com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        retCode_ = value;
        
        return this;
      }
      public Builder clearRetCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retCode_ = com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionResponse.ConnectionHeartbeatDetectionResponse.ResponseRetCode.SUCCESS;
        
        return this;
      }
      
      // required uint32 offlineMessages = 2;
      private int offlineMessages_ ;
      public boolean hasOfflineMessages() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getOfflineMessages() {
        return offlineMessages_;
      }
      public Builder setOfflineMessages(int value) {
        bitField0_ |= 0x00000002;
        offlineMessages_ = value;
        
        return this;
      }
      public Builder clearOfflineMessages() {
        bitField0_ = (bitField0_ & ~0x00000002);
        offlineMessages_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.ConnectionHeartbeatDetectionResponse)
    }
    
    static {
      defaultInstance = new ConnectionHeartbeatDetectionResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.ConnectionHeartbeatDetectionResponse)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
