// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransHeader.proto

package com.aspire.mose.protocol.proto;

public final class MsgTransHeader {
  private MsgTransHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TransHeaderOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string TransactionID = 1;
    boolean hasTransactionID();
    String getTransactionID();
    
    // required uint32 CmdID = 2;
    boolean hasCmdID();
    int getCmdID();
    
    // required uint32 MsgType = 3;
    boolean hasMsgType();
    int getMsgType();
    
    // optional uint32 MsgNumber = 4;
    boolean hasMsgNumber();
    int getMsgNumber();
    
    // optional uint32 MsgSequence = 5;
    boolean hasMsgSequence();
    int getMsgSequence();
  }
  public static final class TransHeader extends
      com.google.protobuf.GeneratedMessageLite
      implements TransHeaderOrBuilder {
    // Use TransHeader.newBuilder() to construct.
    private TransHeader(Builder builder) {
      super(builder);
    }
    private TransHeader(boolean noInit) {}
    
    private static final TransHeader defaultInstance;
    public static TransHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public TransHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string TransactionID = 1;
    public static final int TRANSACTIONID_FIELD_NUMBER = 1;
    private java.lang.Object transactionID_;
    public boolean hasTransactionID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTransactionID() {
      java.lang.Object ref = transactionID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          transactionID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTransactionIDBytes() {
      java.lang.Object ref = transactionID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        transactionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 CmdID = 2;
    public static final int CMDID_FIELD_NUMBER = 2;
    private int cmdID_;
    public boolean hasCmdID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCmdID() {
      return cmdID_;
    }
    
    // required uint32 MsgType = 3;
    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private int msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getMsgType() {
      return msgType_;
    }
    
    // optional uint32 MsgNumber = 4;
    public static final int MSGNUMBER_FIELD_NUMBER = 4;
    private int msgNumber_;
    public boolean hasMsgNumber() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getMsgNumber() {
      return msgNumber_;
    }
    
    // optional uint32 MsgSequence = 5;
    public static final int MSGSEQUENCE_FIELD_NUMBER = 5;
    private int msgSequence_;
    public boolean hasMsgSequence() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getMsgSequence() {
      return msgSequence_;
    }
    
    private void initFields() {
      transactionID_ = "";
      cmdID_ = 0;
      msgType_ = 0;
      msgNumber_ = 0;
      msgSequence_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTransactionID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmdID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTransactionIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, cmdID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, msgType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, msgNumber_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, msgSequence_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTransactionIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, cmdID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, msgType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, msgNumber_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, msgSequence_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader, Builder>
        implements com.aspire.mose.protocol.proto.MsgTransHeader.TransHeaderOrBuilder {
      // Construct using com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        transactionID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        msgNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msgSequence_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader getDefaultInstanceForType() {
        return com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader build() {
        com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader buildPartial() {
        com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader result = new com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transactionID_ = transactionID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmdID_ = cmdID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msgNumber_ = msgNumber_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgSequence_ = msgSequence_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader other) {
        if (other == com.aspire.mose.protocol.proto.MsgTransHeader.TransHeader.getDefaultInstance()) return this;
        if (other.hasTransactionID()) {
          setTransactionID(other.getTransactionID());
        }
        if (other.hasCmdID()) {
          setCmdID(other.getCmdID());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgNumber()) {
          setMsgNumber(other.getMsgNumber());
        }
        if (other.hasMsgSequence()) {
          setMsgSequence(other.getMsgSequence());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTransactionID()) {
          
          return false;
        }
        if (!hasCmdID()) {
          
          return false;
        }
        if (!hasMsgType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              transactionID_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cmdID_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgType_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              msgNumber_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              msgSequence_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string TransactionID = 1;
      private java.lang.Object transactionID_ = "";
      public boolean hasTransactionID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTransactionID() {
        java.lang.Object ref = transactionID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          transactionID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTransactionID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transactionID_ = value;
        
        return this;
      }
      public Builder clearTransactionID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transactionID_ = getDefaultInstance().getTransactionID();
        
        return this;
      }
      void setTransactionID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        transactionID_ = value;
        
      }
      
      // required uint32 CmdID = 2;
      private int cmdID_ ;
      public boolean hasCmdID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCmdID() {
        return cmdID_;
      }
      public Builder setCmdID(int value) {
        bitField0_ |= 0x00000002;
        cmdID_ = value;
        
        return this;
      }
      public Builder clearCmdID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdID_ = 0;
        
        return this;
      }
      
      // required uint32 MsgType = 3;
      private int msgType_ ;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000004;
        msgType_ = value;
        
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgType_ = 0;
        
        return this;
      }
      
      // optional uint32 MsgNumber = 4;
      private int msgNumber_ ;
      public boolean hasMsgNumber() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getMsgNumber() {
        return msgNumber_;
      }
      public Builder setMsgNumber(int value) {
        bitField0_ |= 0x00000008;
        msgNumber_ = value;
        
        return this;
      }
      public Builder clearMsgNumber() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msgNumber_ = 0;
        
        return this;
      }
      
      // optional uint32 MsgSequence = 5;
      private int msgSequence_ ;
      public boolean hasMsgSequence() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getMsgSequence() {
        return msgSequence_;
      }
      public Builder setMsgSequence(int value) {
        bitField0_ |= 0x00000010;
        msgSequence_ = value;
        
        return this;
      }
      public Builder clearMsgSequence() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgSequence_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.TransHeader)
    }
    
    static {
      defaultInstance = new TransHeader(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.TransHeader)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
