// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthClientReq.proto

package com.aspire.mose.protocol.handshake;

public final class MsgAuthClientReq {
  private MsgAuthClientReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AuthClientReqOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string SessionId = 1;
    boolean hasSessionId();
    String getSessionId();
    
    // required .protocol.AuthClientReq.IdCertType IdType = 2;
    boolean hasIdType();
    com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType getIdType();
    
    // required bytes IdCertContent = 3;
    boolean hasIdCertContent();
    com.google.protobuf.ByteString getIdCertContent();
    
    // required string TermMacAddr = 4;
    boolean hasTermMacAddr();
    String getTermMacAddr();
  }
  public static final class AuthClientReq extends
      com.google.protobuf.GeneratedMessageLite
      implements AuthClientReqOrBuilder {
    // Use AuthClientReq.newBuilder() to construct.
    private AuthClientReq(Builder builder) {
      super(builder);
    }
    private AuthClientReq(boolean noInit) {}
    
    private static final AuthClientReq defaultInstance;
    public static AuthClientReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public AuthClientReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum IdCertType
        implements com.google.protobuf.Internal.EnumLite {
      RequestToken(0, 0),
      IdCert(1, 1),
      ;
      
      public static final int RequestToken_VALUE = 0;
      public static final int IdCert_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static IdCertType valueOf(int value) {
        switch (value) {
          case 0: return RequestToken;
          case 1: return IdCert;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<IdCertType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<IdCertType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IdCertType>() {
              public IdCertType findValueByNumber(int number) {
                return IdCertType.valueOf(number);
              }
            };
      
      private final int value;
      
      private IdCertType(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protocol.AuthClientReq.IdCertType)
    }
    
    private int bitField0_;
    // required string SessionId = 1;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    private java.lang.Object sessionId_;
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessionId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .protocol.AuthClientReq.IdCertType IdType = 2;
    public static final int IDTYPE_FIELD_NUMBER = 2;
    private com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType idType_;
    public boolean hasIdType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType getIdType() {
      return idType_;
    }
    
    // required bytes IdCertContent = 3;
    public static final int IDCERTCONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString idCertContent_;
    public boolean hasIdCertContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getIdCertContent() {
      return idCertContent_;
    }
    
    // required string TermMacAddr = 4;
    public static final int TERMMACADDR_FIELD_NUMBER = 4;
    private java.lang.Object termMacAddr_;
    public boolean hasTermMacAddr() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getTermMacAddr() {
      java.lang.Object ref = termMacAddr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          termMacAddr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTermMacAddrBytes() {
      java.lang.Object ref = termMacAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        termMacAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sessionId_ = "";
      idType_ = com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType.RequestToken;
      idCertContent_ = com.google.protobuf.ByteString.EMPTY;
      termMacAddr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdCertContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTermMacAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, idType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, idCertContent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTermMacAddrBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, idType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, idCertContent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTermMacAddrBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq, Builder>
        implements com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReqOrBuilder {
      // Construct using com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        idType_ = com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType.RequestToken;
        bitField0_ = (bitField0_ & ~0x00000002);
        idCertContent_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        termMacAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq getDefaultInstanceForType() {
        return com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq build() {
        com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq buildPartial() {
        com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq result = new com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.idType_ = idType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.idCertContent_ = idCertContent_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.termMacAddr_ = termMacAddr_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq other) {
        if (other == com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasIdType()) {
          setIdType(other.getIdType());
        }
        if (other.hasIdCertContent()) {
          setIdCertContent(other.getIdCertContent());
        }
        if (other.hasTermMacAddr()) {
          setTermMacAddr(other.getTermMacAddr());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSessionId()) {
          
          return false;
        }
        if (!hasIdType()) {
          
          return false;
        }
        if (!hasIdCertContent()) {
          
          return false;
        }
        if (!hasTermMacAddr()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType value = com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000002;
                idType_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              idCertContent_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              termMacAddr_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string SessionId = 1;
      private java.lang.Object sessionId_ = "";
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessionId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionId_ = value;
        
        return this;
      }
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = getDefaultInstance().getSessionId();
        
        return this;
      }
      void setSessionId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        
      }
      
      // required .protocol.AuthClientReq.IdCertType IdType = 2;
      private com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType idType_ = com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType.RequestToken;
      public boolean hasIdType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType getIdType() {
        return idType_;
      }
      public Builder setIdType(com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        idType_ = value;
        
        return this;
      }
      public Builder clearIdType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        idType_ = com.aspire.mose.protocol.handshake.MsgAuthClientReq.AuthClientReq.IdCertType.RequestToken;
        
        return this;
      }
      
      // required bytes IdCertContent = 3;
      private com.google.protobuf.ByteString idCertContent_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasIdCertContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getIdCertContent() {
        return idCertContent_;
      }
      public Builder setIdCertContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        idCertContent_ = value;
        
        return this;
      }
      public Builder clearIdCertContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        idCertContent_ = getDefaultInstance().getIdCertContent();
        
        return this;
      }
      
      // required string TermMacAddr = 4;
      private java.lang.Object termMacAddr_ = "";
      public boolean hasTermMacAddr() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTermMacAddr() {
        java.lang.Object ref = termMacAddr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          termMacAddr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTermMacAddr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        termMacAddr_ = value;
        
        return this;
      }
      public Builder clearTermMacAddr() {
        bitField0_ = (bitField0_ & ~0x00000008);
        termMacAddr_ = getDefaultInstance().getTermMacAddr();
        
        return this;
      }
      void setTermMacAddr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        termMacAddr_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.AuthClientReq)
    }
    
    static {
      defaultInstance = new AuthClientReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.AuthClientReq)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
