// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CertServerResp.proto

package com.aspire.mose.protocol.handshake;

public final class MsgCertServerResp {
  private MsgCertServerResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CertServerRespOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .protocol.ProtocolRetCode RetResult = 1;
    boolean hasRetResult();
    com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult();
    
    // optional uint32 FormatType = 2;
    boolean hasFormatType();
    int getFormatType();
    
    // optional bytes DigiCert = 3;
    boolean hasDigiCert();
    com.google.protobuf.ByteString getDigiCert();
  }
  public static final class CertServerResp extends
      com.google.protobuf.GeneratedMessageLite
      implements CertServerRespOrBuilder {
    // Use CertServerResp.newBuilder() to construct.
    private CertServerResp(Builder builder) {
      super(builder);
    }
    private CertServerResp(boolean noInit) {}
    
    private static final CertServerResp defaultInstance;
    public static CertServerResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public CertServerResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .protocol.ProtocolRetCode RetResult = 1;
    public static final int RETRESULT_FIELD_NUMBER = 1;
    private com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode retResult_;
    public boolean hasRetResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult() {
      return retResult_;
    }
    
    // optional uint32 FormatType = 2;
    public static final int FORMATTYPE_FIELD_NUMBER = 2;
    private int formatType_;
    public boolean hasFormatType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getFormatType() {
      return formatType_;
    }
    
    // optional bytes DigiCert = 3;
    public static final int DIGICERT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString digiCert_;
    public boolean hasDigiCert() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getDigiCert() {
      return digiCert_;
    }
    
    private void initFields() {
      retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
      formatType_ = 0;
      digiCert_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRetResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, retResult_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, formatType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, digiCert_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, retResult_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, formatType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, digiCert_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp, Builder>
        implements com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerRespOrBuilder {
      // Construct using com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        formatType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        digiCert_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp getDefaultInstanceForType() {
        return com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp build() {
        com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp buildPartial() {
        com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp result = new com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retResult_ = retResult_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.formatType_ = formatType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.digiCert_ = digiCert_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp other) {
        if (other == com.aspire.mose.protocol.handshake.MsgCertServerResp.CertServerResp.getDefaultInstance()) return this;
        if (other.hasRetResult()) {
          setRetResult(other.getRetResult());
        }
        if (other.hasFormatType()) {
          setFormatType(other.getFormatType());
        }
        if (other.hasDigiCert()) {
          setDigiCert(other.getDigiCert());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRetResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode value = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                retResult_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              formatType_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              digiCert_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .protocol.ProtocolRetCode RetResult = 1;
      private com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
      public boolean hasRetResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode getRetResult() {
        return retResult_;
      }
      public Builder setRetResult(com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        retResult_ = value;
        
        return this;
      }
      public Builder clearRetResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retResult_ = com.aspire.mose.protocol.handshake.MsgProtocolRetCode.ProtocolRetCode.SUCCESS;
        
        return this;
      }
      
      // optional uint32 FormatType = 2;
      private int formatType_ ;
      public boolean hasFormatType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getFormatType() {
        return formatType_;
      }
      public Builder setFormatType(int value) {
        bitField0_ |= 0x00000002;
        formatType_ = value;
        
        return this;
      }
      public Builder clearFormatType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        formatType_ = 0;
        
        return this;
      }
      
      // optional bytes DigiCert = 3;
      private com.google.protobuf.ByteString digiCert_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasDigiCert() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getDigiCert() {
        return digiCert_;
      }
      public Builder setDigiCert(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        digiCert_ = value;
        
        return this;
      }
      public Builder clearDigiCert() {
        bitField0_ = (bitField0_ & ~0x00000004);
        digiCert_ = getDefaultInstance().getDigiCert();
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.CertServerResp)
    }
    
    static {
      defaultInstance = new CertServerResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.CertServerResp)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
