// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolRetCode.proto

package com.aspire.mose.protocol.handshake;

public final class MsgProtocolRetCode {
  private MsgProtocolRetCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum ProtocolRetCode
      implements com.google.protobuf.Internal.EnumLite {
    SUCCESS(0, 0),
    SYSTEMERROR(1, 1),
    SESSIONIDEXPIRED(2, 11),
    CREDENTIALSEXPIRINGSOON(3, 21),
    CREDENTIALSEXPIRED(4, 22),
    CREDENTIALSILLEGAL(5, 23),
    REQTOKENDUPLICATE(6, 31),
    REQTOKENILLEGAL(7, 32),
    ;
    
    public static final int SUCCESS_VALUE = 0;
    public static final int SYSTEMERROR_VALUE = 1;
    public static final int SESSIONIDEXPIRED_VALUE = 11;
    public static final int CREDENTIALSEXPIRINGSOON_VALUE = 21;
    public static final int CREDENTIALSEXPIRED_VALUE = 22;
    public static final int CREDENTIALSILLEGAL_VALUE = 23;
    public static final int REQTOKENDUPLICATE_VALUE = 31;
    public static final int REQTOKENILLEGAL_VALUE = 32;
    
    
    public final int getNumber() { return value; }
    
    public static ProtocolRetCode valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return SYSTEMERROR;
        case 11: return SESSIONIDEXPIRED;
        case 21: return CREDENTIALSEXPIRINGSOON;
        case 22: return CREDENTIALSEXPIRED;
        case 23: return CREDENTIALSILLEGAL;
        case 31: return REQTOKENDUPLICATE;
        case 32: return REQTOKENILLEGAL;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolRetCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtocolRetCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolRetCode>() {
            public ProtocolRetCode findValueByNumber(int number) {
              return ProtocolRetCode.valueOf(number);
            }
          };
    
    private final int value;
    
    private ProtocolRetCode(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:protocol.ProtocolRetCode)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
