// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageStateRequest.proto

package com.aspire.mose.protocol.proto.msgpush;

public final class MsgMessageStateRequest {
  private MsgMessageStateRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessageStateRequestOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string deviceId = 1;
    boolean hasDeviceId();
    String getDeviceId();
    
    // required string userId = 2;
    boolean hasUserId();
    String getUserId();
    
    // optional string userToken = 3;
    boolean hasUserToken();
    String getUserToken();
    
    // required string appId = 4;
    boolean hasAppId();
    String getAppId();
    
    // required string msgId = 5;
    boolean hasMsgId();
    String getMsgId();
    
    // required .protocol.MessageStateRequest.MessageState msgState = 6;
    boolean hasMsgState();
    com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState getMsgState();
  }
  public static final class MessageStateRequest extends
      com.google.protobuf.GeneratedMessageLite
      implements MessageStateRequestOrBuilder {
    // Use MessageStateRequest.newBuilder() to construct.
    private MessageStateRequest(Builder builder) {
      super(builder);
    }
    private MessageStateRequest(boolean noInit) {}
    
    private static final MessageStateRequest defaultInstance;
    public static MessageStateRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageStateRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum MessageState
        implements com.google.protobuf.Internal.EnumLite {
      DELIVRD(0, 0),
      ACCEPTD(1, 1),
      EXPIRED(2, 2),
      REJECTD(3, 3),
      ;
      
      public static final int DELIVRD_VALUE = 0;
      public static final int ACCEPTD_VALUE = 1;
      public static final int EXPIRED_VALUE = 2;
      public static final int REJECTD_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static MessageState valueOf(int value) {
        switch (value) {
          case 0: return DELIVRD;
          case 1: return ACCEPTD;
          case 2: return EXPIRED;
          case 3: return REJECTD;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageState>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageState>() {
              public MessageState findValueByNumber(int number) {
                return MessageState.valueOf(number);
              }
            };
      
      private final int value;
      
      private MessageState(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protocol.MessageStateRequest.MessageState)
    }
    
    private int bitField0_;
    // required string deviceId = 1;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string userToken = 3;
    public static final int USERTOKEN_FIELD_NUMBER = 3;
    private java.lang.Object userToken_;
    public boolean hasUserToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getUserToken() {
      java.lang.Object ref = userToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserTokenBytes() {
      java.lang.Object ref = userToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string appId = 4;
    public static final int APPID_FIELD_NUMBER = 4;
    private java.lang.Object appId_;
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          appId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string msgId = 5;
    public static final int MSGID_FIELD_NUMBER = 5;
    private java.lang.Object msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msgId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .protocol.MessageStateRequest.MessageState msgState = 6;
    public static final int MSGSTATE_FIELD_NUMBER = 6;
    private com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState msgState_;
    public boolean hasMsgState() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState getMsgState() {
      return msgState_;
    }
    
    private void initFields() {
      deviceId_ = "";
      userId_ = "";
      userToken_ = "";
      appId_ = "";
      msgId_ = "";
      msgState_ = com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState.DELIVRD;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAppIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, msgState_.getNumber());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAppIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, msgState_.getNumber());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest, Builder>
        implements com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequestOrBuilder {
      // Construct using com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        appId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        msgState_ = com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState.DELIVRD;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest getDefaultInstanceForType() {
        return com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest build() {
        com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest buildPartial() {
        com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest result = new com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userToken_ = userToken_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgState_ = msgState_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest other) {
        if (other == com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserToken()) {
          setUserToken(other.getUserToken());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasMsgState()) {
          setMsgState(other.getMsgState());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (!hasMsgId()) {
          
          return false;
        }
        if (!hasMsgState()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userToken_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              appId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msgId_ = input.readBytes();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState value = com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000020;
                msgState_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string deviceId = 1;
      private java.lang.Object deviceId_ = "";
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        
        return this;
      }
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        
        return this;
      }
      void setDeviceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        
      }
      
      // required string userId = 2;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userId_ = value;
        
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = getDefaultInstance().getUserId();
        
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        
      }
      
      // optional string userToken = 3;
      private java.lang.Object userToken_ = "";
      public boolean hasUserToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getUserToken() {
        java.lang.Object ref = userToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userToken_ = value;
        
        return this;
      }
      public Builder clearUserToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userToken_ = getDefaultInstance().getUserToken();
        
        return this;
      }
      void setUserToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        userToken_ = value;
        
      }
      
      // required string appId = 4;
      private java.lang.Object appId_ = "";
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAppId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        appId_ = value;
        
        return this;
      }
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        appId_ = getDefaultInstance().getAppId();
        
        return this;
      }
      void setAppId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        appId_ = value;
        
      }
      
      // required string msgId = 5;
      private java.lang.Object msgId_ = "";
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsgId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgId_ = value;
        
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgId_ = getDefaultInstance().getMsgId();
        
        return this;
      }
      void setMsgId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        msgId_ = value;
        
      }
      
      // required .protocol.MessageStateRequest.MessageState msgState = 6;
      private com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState msgState_ = com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState.DELIVRD;
      public boolean hasMsgState() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState getMsgState() {
        return msgState_;
      }
      public Builder setMsgState(com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        msgState_ = value;
        
        return this;
      }
      public Builder clearMsgState() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgState_ = com.aspire.mose.protocol.proto.msgpush.MsgMessageStateRequest.MessageStateRequest.MessageState.DELIVRD;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.MessageStateRequest)
    }
    
    static {
      defaultInstance = new MessageStateRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.MessageStateRequest)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
