// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc/ConnectionHeartbeatDetectionRequest.proto

package com.aspire.mose.protocol.proto;

public final class MsgConnectionHeartbeatDetectionRequest {
  private MsgConnectionHeartbeatDetectionRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ConnectionHeartbeatDetectionRequestOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string deviceId = 1;
    boolean hasDeviceId();
    String getDeviceId();
  }
  public static final class ConnectionHeartbeatDetectionRequest extends
      com.google.protobuf.GeneratedMessageLite
      implements ConnectionHeartbeatDetectionRequestOrBuilder {
    // Use ConnectionHeartbeatDetectionRequest.newBuilder() to construct.
    private ConnectionHeartbeatDetectionRequest(Builder builder) {
      super(builder);
    }
    private ConnectionHeartbeatDetectionRequest(boolean noInit) {}
    
    private static final ConnectionHeartbeatDetectionRequest defaultInstance;
    public static ConnectionHeartbeatDetectionRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConnectionHeartbeatDetectionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string deviceId = 1;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      deviceId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest, Builder>
        implements com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequestOrBuilder {
      // Construct using com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest getDefaultInstanceForType() {
        return com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest.getDefaultInstance();
      }
      
      public com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest build() {
        com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest buildPartial() {
        com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest result = new com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest other) {
        if (other == com.aspire.mose.protocol.proto.MsgConnectionHeartbeatDetectionRequest.ConnectionHeartbeatDetectionRequest.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string deviceId = 1;
      private java.lang.Object deviceId_ = "";
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        
        return this;
      }
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        
        return this;
      }
      void setDeviceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.ConnectionHeartbeatDetectionRequest)
    }
    
    static {
      defaultInstance = new ConnectionHeartbeatDetectionRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.ConnectionHeartbeatDetectionRequest)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
